# forge CLI wrapper — generated by agent_forge scaffold.
#
# One-time setup (once per machine):
#   uv tool install --editable <path-to-agent_forge>
# Verify:
#   forge --help
#
# After setup, all targets below work from this directory with no extra env vars.

export FORGE_TARGET_PROJECT_ROOT := $(shell pwd)

.PHONY: help status boards adapt viz \
        flow0 flow1 flow2 flow3 flow4 run-all

help:  ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | \
	  awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-14s\033[0m %s\n",$$1,$$2}'

# ---------- observability ----------

status:  ## Print crew board status dashboard
	forge status

boards:  ## Regenerate tasks/boards_viz.html  (same as: forge viz)
	python3 tools/build_boards_viz.py

viz:  ## Alias for boards
	forge viz

# ---------- flows ----------

flow0:  ## Triage intake ticket         usage: make flow0 TICKET=SM-001
	forge flow0 $(if $(TICKET),--ticket $(TICKET),)

flow1:  ## Sprint planning              usage: make flow1 GOAL="Ship login screen"
	forge flow1 $(if $(GOAL),--goal '$(GOAL)',)

flow2:  ## Task breakdown               usage: make flow2 TICKET=AR-001
	forge flow2 $(if $(TICKET),--ticket $(TICKET),)

flow3:  ## Execute task                 usage: make flow3 TICKET=IM-001
	forge flow3 $(if $(TICKET),--ticket $(TICKET),)

flow4:  ## Prompt improvement
	forge flow4 $(if $(TICKET),--ticket $(TICKET),)

run-all:  ## Run all pending tasks (sequential)
	forge run-all

# ---------- pack ----------

adapt:  ## Re-analyse repo and save updated pack (dry-run first)
	forge adapt
