import { useCallback, useEffect, useRef, useState } from "react"
import { BookOpen, Heart, History, MessageCircle, Search, Send } from "lucide-react"
import { Badge, type BadgeProps } from "./components/ui/badge"

type Topic = { name: string; variant: NonNullable<BadgeProps["variant"]> }
type Post = { id: string; era: string; date: string; headline: string; content: string; likes: number; comments: number; shares?: number; source: string; sourceUrl?: string; topics: Topic[] }

const initialPosts: Post[] = [
  { id: "moon", era: "July 20, 1969", date: "56 years ago", headline: "Humanity steps onto the Moon", content: "At 10:56 p.m. EDT, Neil Armstrong became the first person to walk on the Moon. An estimated 650 million people watched the broadcast — then the largest television audience in history.", likes: 12400, comments: 892, shares: 318, source: "Apollo 11 mission archive", sourceUrl: "https://www.nasa.gov/mission/apollo-11/", topics: [{ name: "Science", variant: "science" }, { name: "USA", variant: "usa" }] },
  { id: "press", era: "May 3, 1791", date: "234 years ago", headline: "The first press-freedom amendment is adopted", content: "The First Amendment entered the United States Constitution, protecting freedoms of religion, speech, press, assembly, and petition. Its 45 words would shape public life far beyond its original moment.", likes: 7300, comments: 426, shares: 187, source: "U.S. National Archives", sourceUrl: "https://www.archives.gov/founding-docs/bill-of-rights", topics: [{ name: "USA", variant: "usa" }] },
]

const facts: Omit<Post, "id" | "date" | "likes" | "comments">[] = [
  { era: "November 9, 1989", headline: "The Berlin Wall opens", content: "A mistaken announcement at an evening press conference led East Germans to the border crossings. Within hours, crowds were crossing freely, beginning the peaceful end of a divided Berlin.", shares: 241, source: "German Historical Museum", sourceUrl: "https://www.dhm.de/en/", topics: [{ name: "WW2", variant: "ww2" }] },
  { era: "December 17, 1903", headline: "The first powered flight lasts 12 seconds", content: "Near Kitty Hawk, North Carolina, Orville Wright flew 120 feet in the Wright Flyer. The brothers made four flights that day; the last stayed aloft for 59 seconds.", shares: 159, source: "Smithsonian National Air and Space Museum", sourceUrl: "https://airandspace.si.edu/", topics: [{ name: "Science", variant: "science" }, { name: "USA", variant: "usa" }] },
  { era: "October 24, 1945", headline: "The United Nations officially begins", content: "Fifty-one countries brought the United Nations Charter into force, creating an organization designed to maintain peace and foster cooperation after the devastation of World War II.", shares: 96, source: "United Nations archives", sourceUrl: "https://www.un.org/en/about-us/history-of-the-un", topics: [{ name: "WW2", variant: "ww2" }] },
  { era: "April 12, 1961", headline: "Yuri Gagarin orbits the Earth", content: "Vostok 1 completed a single orbit in 108 minutes, making Gagarin the first human in space. His call sign, Kedr, means cedar in Russian.", shares: 132, source: "Roscosmos historical collection", sourceUrl: "https://www.roscosmos.ru/en/", topics: [{ name: "Science", variant: "science" }] },
  { era: "August 1, 1981", headline: "MTV makes music videos a shared ritual", content: "MTV launched in the United States with the words, 'Ladies and gentlemen, rock and roll.' The channel helped turn music videos into a defining force in global pop culture.", shares: 208, source: "Museum of Pop Culture", sourceUrl: "https://www.mopop.org/", topics: [{ name: "2000s Pop Culture", variant: "popCulture" }] },
  { era: "August 21, 1911", headline: "The Mona Lisa disappears from the Louvre", content: "The painting was stolen by a former museum employee and remained missing for more than two years. The sensational theft helped make Leonardo da Vinci's portrait famous around the world.", shares: 114, source: "Louvre Museum archives", sourceUrl: "https://www.louvre.fr/en/", topics: [{ name: "Art", variant: "art" }] },
]

const format = (value: number) => value >= 1000 ? `${(value / 1000).toFixed(value >= 10000 ? 0 : 1)}K` : value.toString()
function AdminMark() { return <div aria-hidden="true" className="admin-mark"><History className="size-5" /></div> }

function SkeletonCard() { return <div className="rounded-2xl border border-line bg-white p-5 shadow-[0_5px_24px_rgba(28,38,63,.05)]"><div className="mb-5 flex gap-3"><div className="shimmer size-10 rounded-xl"/><div className="flex-1 space-y-2 pt-1"><div className="shimmer h-3.5 w-28 rounded"/><div className="shimmer h-3 w-20 rounded"/></div></div><div className="space-y-3"><div className="shimmer h-3 w-24 rounded"/><div className="shimmer h-6 w-4/5 rounded"/><div className="shimmer h-4 w-full rounded"/><div className="shimmer h-4 w-11/12 rounded"/></div><div className="mt-6 flex justify-between border-t border-line/60 pt-4"><div className="shimmer h-5 w-24 rounded"/><div className="shimmer h-5 w-32 rounded"/></div></div> }

function PostCard({ post }: { post: Post }) {
  const [expanded, setExpanded] = useState(false)
  const long = post.content.length > 180
  const copy = !expanded && long ? `${post.content.slice(0, 180).trimEnd()}…` : post.content
  return <article className="history-card rounded-2xl border border-line bg-white shadow-[0_5px_24px_rgba(28,38,63,.05)]"><div className="p-5 sm:p-6"><header className="mb-5 flex items-start justify-between"><div className="flex min-w-0 items-center gap-3"><AdminMark/><div><h2 className="font-brand text-sm font-bold text-ink">Anon Admin</h2><p className="flex items-center gap-1 text-xs text-muted"><BookOpen className="size-3"/> Historical record · {post.date}</p></div></div></header><div className="border-l-2 border-brand/70 pl-4"><div className="mb-3 flex flex-wrap gap-2">{post.topics.map((topic) => <Badge key={topic.name} variant={topic.variant}>{topic.name}</Badge>)}</div><p className="mb-2 font-brand text-xs font-bold uppercase tracking-[0.14em] text-brand">On this day · {post.era}</p><h3 className="font-brand text-[21px] font-extrabold leading-[1.22] tracking-tight text-ink sm:text-[24px]">{post.headline}</h3><p className="mt-3 text-[16px] leading-6 text-slate-700">{copy}{long && <button onClick={() => setExpanded(!expanded)} className="ml-1 cursor-pointer font-semibold text-brand underline underline-offset-2 hover:text-brand/80">{expanded ? "See less" : "See more"}</button>}</p></div><p className="mt-5 border-t border-line/60 pt-3 text-xs font-medium text-muted">Source: {post.sourceUrl ? <a href={post.sourceUrl} target="_blank" rel="noopener noreferrer" className="cursor-pointer text-brand underline underline-offset-2 hover:text-brand/80">{post.source}</a> : post.source}</p></div><div className="flex items-center gap-8 border-t border-line/60 px-5 py-3 text-sm text-muted sm:px-6"><span className="flex items-center gap-1.5"><Heart className="size-4"/>{format(post.likes)}</span><span className="flex items-center gap-1.5"><MessageCircle className="size-4"/>{format(post.comments)}</span>{post.shares && <span className="flex items-center gap-1.5"><Send className="size-4"/>{post.shares}</span>}</div></article>
}


function App() {
  const [posts, setPosts] = useState<Post[]>([]), [loading, setLoading] = useState(true), [moreLoading, setMoreLoading] = useState(false)
  const sentinel = useRef<HTMLDivElement>(null), page = useRef(0), locked = useRef(false)
  const load = useCallback((first = false) => { if (locked.current) return; locked.current = true; first ? setLoading(true) : setMoreLoading(true); window.setTimeout(() => { const newPosts = Array.from({ length: first ? 2 : 3 }, (_, i) => { const index = page.current * 3 + i; const fact = facts[index % facts.length]; return { ...fact, id: `post-${index}`, date: `${Math.floor(index / 2) + 1} days ago`, likes: 540 + index * 291, comments: 23 + index * 17 } }); page.current += 1; setPosts(first ? initialPosts : old => [...old, ...newPosts]); setLoading(false); setMoreLoading(false); locked.current = false }, first ? 700 : 900) }, [])
  useEffect(() => { load(true) }, [load])
  useEffect(() => { const node = sentinel.current; if (!node) return; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting && !loading) load() }, { rootMargin: "280px" }); observer.observe(node); return () => observer.disconnect() }, [load, loading])
  return <><header className="sticky top-0 z-20 border-b border-line bg-white/95 px-4 backdrop-blur sm:px-6"><div className="mx-auto flex h-16 max-w-[760px] items-center justify-between"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-brand text-white"><History className="size-5"/></span><span className="font-brand text-xl font-black tracking-tight text-ink">LearnScroll</span><label className="hidden items-center gap-2 rounded-full bg-page px-3 py-2 md:flex"><Search className="size-4 text-muted"/><input placeholder="Search history" className="w-40 border-0 bg-transparent text-sm outline-none"/></label></div></div></header><main className="mx-auto flex min-h-screen w-full max-w-[712px] flex-col gap-4 px-3 py-6 pb-24 sm:px-4 md:pb-8"><div className="mb-1 px-2"><p className="font-brand text-xs font-bold uppercase tracking-[0.16em] text-brand">Daily dispatches from the past</p><p className="mt-1 text-sm text-muted">A timeline worth scrolling through.</p></div>{loading ? Array.from({ length: 3 }, (_, i) => <SkeletonCard key={i}/>) : posts.map(post => <PostCard key={post.id} post={post}/>)}{moreLoading && Array.from({ length: 3 }, (_, i) => <SkeletonCard key={i}/>)}<div ref={sentinel} className="h-4"/></main></>
}

export default App
