import { useCallback, useEffect, useRef, useState } from "react"
import { Bell, Ellipsis, Heart, Home, Menu, MessageCircle, Search, Send, ShoppingBag, ThumbsUp, UsersRound, Video } from "lucide-react"
import { Button } from "./components/ui/button"

type Post = { id: string; title: string; date: string; content: string; likes: number; comments: number; shares?: number; avatar: string; images?: string[] }

const images = {
  solar: "https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1400&q=85",
  city1: "https://images.unsplash.com/photo-1519608487953-e999c86e7450?auto=format&fit=crop&w=900&q=85",
  city2: "https://images.unsplash.com/photo-1520483601560-389dff434fdf?auto=format&fit=crop&w=900&q=85",
}
const avatars = ["https://i.pravatar.cc/150?img=32", "https://i.pravatar.cc/150?img=47", "https://i.pravatar.cc/150?img=12", "https://i.pravatar.cc/150?img=5"]

const initialPosts: Post[] = [
  { id: "world", title: "World Today", date: "2 hours ago", avatar: avatars[0], likes: 4200, comments: 1300, shares: 83, images: [images.solar], content: "Groundbreaking discovery in renewable energy technology could pave the way for a 100% sustainable future by 2040. Researchers have developed a new material that doubles the efficiency of standard solar panels while reducing production costs significantly. This breakthrough is expected to transform global energy markets." },
  { id: "sarah", title: "Sarah Miller", date: "5 hours ago", avatar: avatars[1], likes: 856, comments: 42, images: [images.city1, images.city2], content: "Just finished my latest urban photography series. The city lights at 3 AM hit differently. ✨ 📸" },
]
const generated = ["A curious note from today: the best ideas often arrive after the first draft.", "Small progress is still progress. What are you learning this week?", "Spent the afternoon following an unexpected rabbit hole — and found exactly what I needed.", "A quick reminder that curiosity is a muscle. Keep using it."]
const format = (value: number) => value >= 1000 ? `${(value / 1000).toFixed(1)}k` : value.toString()

function SkeletonCard() { return <div className="rounded-xl border border-line bg-white p-5 shadow-sm"><div className="mb-5 flex gap-3"><div className="shimmer size-11 rounded-full"/><div className="flex-1 space-y-2.5 pt-0.5"><div className="shimmer h-4 w-2/5 rounded"/><div className="shimmer h-3 w-1/4 rounded"/></div></div><div className="space-y-3.5"><div className="shimmer h-4 w-full rounded"/><div className="shimmer h-4 w-11/12 rounded"/><div className="shimmer h-4 w-3/4 rounded"/></div><div className="mt-6 flex justify-between border-t border-line/40 pt-4"><div className="shimmer h-8 w-20 rounded-lg"/><div className="shimmer h-8 w-20 rounded-lg"/><div className="shimmer h-8 w-20 rounded-lg"/></div></div> }

function PostCard({ post }: { post: Post }) {
  const [expanded, setExpanded] = useState(false)
  const long = post.content.length > 145
  const text = !expanded && long ? `${post.content.slice(0, 145).trimEnd()}...` : post.content
  return <article className="overflow-hidden rounded-xl border border-line bg-white shadow-sm"><div className="p-5"><div className="mb-4 flex items-start justify-between"><div className="flex min-w-0 gap-3"><img src={post.avatar} alt="" className="size-11 rounded-full border border-line object-cover"/><div className="min-w-0"><h2 className="truncate font-brand text-base font-bold">{post.title}</h2><p className="text-sm text-muted">{post.date}</p></div></div><Button variant="ghost" size="icon" aria-label="Post menu" className="size-9 text-muted"><Ellipsis className="size-5"/></Button></div><p className="text-[16px] leading-6">{text}{long && <button onClick={() => setExpanded(!expanded)} className="ml-1 font-bold text-brand hover:underline">{expanded ? "See less" : "See more"}</button>}</p></div>{post.images && <div className={post.images.length > 1 ? "grid h-64 grid-cols-2 gap-1" : "h-80"}>{post.images.map((image) => <img key={image} src={image} alt="Post visual" className="size-full object-cover"/>)}</div>}<div className="px-5 py-4"><div className="mb-4 flex items-center justify-between text-sm text-muted"><div className="flex items-center gap-2"><span className="flex -space-x-1.5"><span className="flex size-5 items-center justify-center rounded-full border border-white bg-blue-700"><ThumbsUp className="size-2.5 fill-white text-white"/></span>{post.likes > 1000 && <span className="flex size-5 items-center justify-center rounded-full border border-white bg-red-500"><Heart className="size-2.5 fill-white text-white"/></span>}</span>{format(post.likes)}</div><div className="flex gap-4"><span>{format(post.comments)} comments</span>{post.shares && <span>{post.shares} shares</span>}</div></div><div className="border-t border-line/50 pt-1"><div className="flex"><Action icon={ThumbsUp} label="Like"/><Action icon={MessageCircle} label="Comment"/><Action icon={Send} label="Share"/></div></div></div></article>
}
function Action({ icon: Icon, label }: { icon: typeof ThumbsUp; label: string }) { return <Button variant="ghost" className="h-10 flex-1 gap-2 text-muted hover:bg-slate-100"><Icon className="size-[18px]"/>{label}</Button> }

function App() {
  const [posts, setPosts] = useState<Post[]>([]), [loading, setLoading] = useState(true), [moreLoading, setMoreLoading] = useState(false)
  const sentinel = useRef<HTMLDivElement>(null), page = useRef(0), locked = useRef(false)
  const load = useCallback((first = false) => { if (locked.current) return; locked.current = true; first ? setLoading(true) : setMoreLoading(true); window.setTimeout(() => { const newPosts = Array.from({ length: first ? 2 : 3 }, (_, i) => { const index = page.current * 3 + i; return { id: `post-${index}`, title: ["Alex Rivera", "Maya Chen", "Jordan Lee"][index % 3], date: `${index + 1} hours ago`, avatar: avatars[(index + 2) % avatars.length], likes: 137 + index * 83, comments: 8 + index * 5, content: generated[index % generated.length] } }); page.current += 1; setPosts(first ? initialPosts : old => [...old, ...newPosts]); setLoading(false); setMoreLoading(false); locked.current = false }, first ? 850 : 1100) }, [])
  useEffect(() => { load(true) }, [load])
  useEffect(() => { const node = sentinel.current; if (!node) return; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting && !loading) load() }, { rootMargin: "280px" }); observer.observe(node); return () => observer.disconnect() }, [load, loading])
  return <><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-line bg-white px-4 sm:px-6"><div className="flex items-center gap-4"><span className="font-brand text-2xl font-black tracking-tight text-brand">LearnScroll</span><label className="hidden items-center gap-3 rounded-full bg-slate-100 px-4 py-2 md:flex"><Search className="size-4 text-slate-500"/><input placeholder="Search Connect" className="w-52 border-0 bg-transparent text-sm outline-none"/></label></div><div className="flex items-center gap-1 sm:gap-2"><Button size="icon" variant="ghost" className="rounded-full"><MessageCircle className="size-5"/></Button><Button size="icon" variant="ghost" className="rounded-full"><Bell className="size-5"/></Button><img src={avatars[3]} alt="Your profile" className="ml-1 size-10 rounded-full border border-line object-cover"/></div></header><main className="mx-auto flex min-h-screen w-full max-w-[712px] flex-col gap-6 px-0 py-6 pb-24 md:px-4 md:pb-6">{loading ? Array.from({ length: 3 }, (_, i) => <SkeletonCard key={i}/>) : posts.map(post => <PostCard key={post.id} post={post}/>)}{moreLoading && Array.from({ length: 3 }, (_, i) => <SkeletonCard key={i}/>)}<div ref={sentinel} className="h-4"/></main><MobileNav/></>
}
function MobileNav() { const items = [[Home, "Home"], [UsersRound, "Friends"], [Video, "Watch"], [ShoppingBag, "Market"], [Menu, "Menu"]] as const; return <nav className="fixed inset-x-0 bottom-0 z-20 flex h-16 items-center justify-around border-t border-line bg-white md:hidden">{items.map(([Icon, label], index) => <button key={label} className={`flex flex-col items-center gap-1 text-[11px] ${index === 0 ? "font-semibold text-brand" : "text-muted"}`}><Icon className={`size-5 ${index === 0 ? "fill-brand" : ""}`}/>{label}</button>)}</nav> }
export default App
